// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZInZ58NP-osieR3LgHif5eaU7fH5CNq4',
    appId: '1:314915813091:web:610f87490578431d4a77d6',
    messagingSenderId: '314915813091',
    projectId: 'student-exit',
    authDomain: 'student-exit.firebaseapp.com',
    storageBucket: 'student-exit.firebasestorage.app',
    measurementId: 'G-2BCF55PBEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNflSxL9mkbaUHIpD4ed8q8s70K7aLjLI',
    appId: '1:314915813091:android:1ad318f1c119385e4a77d6',
    messagingSenderId: '314915813091',
    projectId: 'student-exit',
    storageBucket: 'student-exit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABJ7t-H-xCc33B_0KbUydcRAE72_gKLNQ',
    appId: '1:314915813091:ios:60bf39d58ed487f84a77d6',
    messagingSenderId: '314915813091',
    projectId: 'student-exit',
    storageBucket: 'student-exit.firebasestorage.app',
    iosBundleId: 'com.example.studentexitsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABJ7t-H-xCc33B_0KbUydcRAE72_gKLNQ',
    appId: '1:314915813091:ios:60bf39d58ed487f84a77d6',
    messagingSenderId: '314915813091',
    projectId: 'student-exit',
    storageBucket: 'student-exit.firebasestorage.app',
    iosBundleId: 'com.example.studentexitsystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZInZ58NP-osieR3LgHif5eaU7fH5CNq4',
    appId: '1:314915813091:web:05235eebc5f699344a77d6',
    messagingSenderId: '314915813091',
    projectId: 'student-exit',
    authDomain: 'student-exit.firebaseapp.com',
    storageBucket: 'student-exit.firebasestorage.app',
    measurementId: 'G-K9BXZXLCZH',
  );
}
